### ISSUE TITLE
Errors while getting list of S3 buckets named in virtual hosting format

### ISSUE THREAD

**Issue by wizard432** [iSECPartners/Scout2#18] opened 2015-06-30 10:24 UTC
Hi, 

I have couple of S3 buckets used as static websites with names like "devs.mydomain.com".
This is the error message when Scout2 tries to enumerate through buckets:

```
BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
hostname u'devs.mydomain.com.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```

There are no upper-case letters in the bucket names.

**Comment by l01cd3v** [comment] 2015-07-01 16:28
I created a bucket named "devs.mydomain.com" and enabled static website hosting on it but cannot reproduce the issue. Did you use a particular option? Can you share the command line you ran?

**Comment by wizard432** [comment] 2015-07-02 12:56
Sure. The command used is default
```
python Scout2.py
```
I've examined my buckets and it seems that the problem is only with "dotted" ones, these which include dots in the bucket name. That is the only thing which they have in common.
Configuration of static websites differ.
Regions differ too.

Again here is the end of log (I've replaced bucket names with color.mydomain.com)
```
Fetching S3 buckets data...
BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
22/53hostname u'red.mydomain.com.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
hostname u'green.mydomain.com.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
hostname u'blue.mydomain.com.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
hostname u'yellow.mydomain.media.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
hostname u'pink.mydomain.com.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```

**Comment by l01cd3v** [comment] 2015-07-04 01:27
Which version of Python and boto are you using? On what OS?

**Comment by wizard432** [comment] 2015-07-07 14:26
Python 2.7.9 on Amazon Linux

Boto libs:
python27-boto.noarch                2.38.0-1.7.amzn1               @amzn-updates
python27-botocore.noarch            1.0.0-0.1.b3.14.amzn1          @amzn-updates

I've also tried with Ubuntu. There is another error message at the end of the request.

Python 2.7.6 on Ubuntu 14
Boto libs:
python-boto 2.20.1-2ubuntu2

Ubuntu error log
```
Fetching S3 buckets data...
label empty or too long
 BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
 BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
 BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
 BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
 BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>563B659592E356BC</RequestId><HostId>zOhXcHicqczie32oUCR8h/wkN8ZS++BpJ7EJO+A1t20pb0tpaEWpoZAOiwMFAXQuZwvxG960Wxo=</HostId></Error>
31/88BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.
```

**Comment by l01cd3v** [comment] 2015-07-31 19:11
Sorry for the delayed response. I am unable to reproduce this issue. Would you mind trying the latest version of Scout2? I migrated away from boto to use boto3.

**Comment by l01cd3v** [comment] 2015-08-17 06:39
Closing for now

**Closed by l01cd3v** 2015-08-17 06:39 UTC
