### ISSUE TITLE
Unable to read and report on cloudtrail data

### ISSUE THREAD

**Issue by michaelcoyote** [iSECPartners/Scout2#66] opened 2016-01-20 01:33 UTC
Everything else reports fine, but when I turned on CloudTrail, I get these errors.
```
Fetching CloudTrail data...
An error occurred (TrailNotFoundException) when calling the GetTrailStatus operation: Unknown trail: bucket_name for the user: 999999999999
...
```

**Comment by michaelcoyote** [comment] 2016-01-20 01:53
As a note, I am using the Scout2 policy within a Group to allow access..

https://github.com/iSECPartners/AWS-recipes/blob/master/IAM-Policies/Scout2-Default.json

**Comment by l01cd3v** [comment] 2016-01-20 02:17
I believe that the issue is because your trail is multi-region. I have seen similar error messages when developing the new version of the tool / testing multi-region trails. I hope to merge this dev branch soon so hopefully this will be fixed then.

**Comment by michaelcoyote** [comment] 2016-01-20 04:28
This is indeed a multi region trail.  If you want I can pull a different branch and test.

**Comment by l01cd3v** [comment] 2016-01-20 14:21
The branch is not stable and I haven't released the new version of opinel that it needs. I'll update this issue as soon as I do the merge / have released enough to be tested.

**Comment by michaelcoyote** [comment] 2016-01-20 17:49
Ok, that's fine.  Keep in mind that this is my test/eval instance and not prod.  I'd be happy to test things if it helps.  Thanks for your quick responses!  :+1:

**Comment by l01cd3v** [comment] 2016-01-30 02:21
Hi Michael,

I just released the RC0 for Scout2 v2.0.0 (yeah, decided to start versioning the tool...). You can get it with the following commands:

git clone https://github.com/iSECPartners/Scout2.git
git checkout tags/v2.0.0rc0
(sudo) pip install -r requirements.txt

I hope to have several people test it within the week, fix whatever bugs there might be, and release v2.0.0 right after. If you see any issues, please open a new issue. If this version fixes this issue, please close it / confirm it's fixed :)

Thanks !

**Comment by michaelcoyote** [comment] 2016-01-30 17:28
Ok, will do.. It may be Monday before I get a chance, but I'm excited to try it out.  Thanks!

**Comment by michaelcoyote** [comment] 2016-02-01 23:09
This appears to have resolved the issue. Thanks!

**Comment by l01cd3v** [comment] 2016-02-02 20:11
Thanks !

**Closed by l01cd3v** 2016-02-02 20:11 UTC
